version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mapf"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dlt4sf3rwpnt"
s3_prefix = "mapf"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
